### ISSUE TITLE
UI updates to profile info dialogue

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#103]
add profile description
remove "enabled" column

**Comment by alexhuang091** [comment]
questions:
1. enabled is removed so only enabled filters will be shown. How if a category has no enabled filter? Still show the category and show no filters?
2. Every category needed to be shown no matter it's enabled or not, no matter it has enabled filters or not, right?

**Comment by M-Nicholls** [comment]
looks good, the filter group name just needs to be bolded to differentiate it from the description:

**Outliers**
Environmental outliers are excluded
