### ISSUE TITLE
DQ filters applied in spatial portal

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#105]
When clicking view in spatial portal from the map tab ensure the DQ filters are applied when data is transferred to the spatial portal

checking with @Tasilee on how this should be handled

**Comment by Tasilee** [comment]
Discussed with @adam-collins and we figure it has to be WYSIWYG: data as filtered sent to SP. The filters will only be **implicit** in viewing the records and any subsequent filtering. For example, a filtered out class will not be present in the dataset when further filtering is used. Ideally, we would want to capture the filter states as supplied to the SP in the dataset metadata (i), i.e., make it explicit.

**Comment by M-Nicholls** [comment]
initially - show a pop up that the DQ filters will not be applied, any user query is still applied (not just all records with no filtering at all) https://github.com/AtlasOfLivingAustralia/DataQuality/issues/118

secondary - data is transferred with the DQ filters and any user filters applied (what the user was viewing in the biocache is what they then get in the spatial portal)

additional - any further implementation of hte DQ filters in the Spatial portal
e.g. 
metadata on the DQ filters

**Comment by M-Nicholls** [comment]
Developed in: https://github.com/AtlasOfLivingAustralia/DataQuality/issues/132
