### ISSUE TITLE
Extract DQ filter functionality into separate standalone service

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/DataQuality#107]
Adding for an issue to track this discussion started with Simon and Miles.

We should look into the potential of pulling most of the DQ functionality into a separate standalone service.  It may serve us well to tackle this prior to further integration of DQ filters into other ALA components as covered in these issues:

https://github.com/AtlasOfLivingAustralia/DataQuality/issues/105
https://github.com/AtlasOfLivingAustralia/DataQuality/issues/74

The bulk of the DQ functionality could be implemented as a separate tool which supports an admin interface for the configuration and web services for integration in front end apps.  With this approach we can keep `biocache-hubs` as a front end only application (with no DB/Backend).  This may prove important when we tackle stage 3 of the infrastructure project which look into the feasibility of replacing `biocache-hubs` with GBIF’s front end and web services  (this is all subject to a scoping exercise).

**Comment by M-Nicholls** [comment]
Take out the admin DQ controller -> new project with domain objects etc
Quality service moved across and webservice UI in front of the methods and code
Webservice client for accessing the methods - retrofit based
ALA hub - replace and use of the service with the webservice client equivalent call
ALA install for deployment
put a copy on current server

**Comment by M-Nicholls** [comment]
Has been completely split out into the tickets listed above
