### ISSUE TITLE
populate or update the biocache field descriptions

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#109]
for the remaining fields

populate or improve the biocache field descriptions (https://biocache.ala.org.au/fields?filter=) where the description is not sufficient to describe the DQ filter fields

**Comment by Tasilee** [comment]
About time :)

**Comment by M-Nicholls** [comment]
moved to here: https://github.com/AtlasOfLivingAustralia/DataQuality/issues/87
