### ISSUE TITLE
New client for DQ project

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#112]
Webservice client for accessing the methods - retrofit based

generate reusable library component project for the API in https://github.com/AtlasOfLivingAustralia/DataQuality/issues/111
move DTOs out into the new component (so code is sharable between client and server)

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/data-quality-filter-service-client/review/DQFSC-CR-1
