### ISSUE TITLE
DQ filter full test plan

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#115]
write up end-to-end DQ filter test plan for move to new project and pre release testing
consider living atlases

**Comment by RobinaSanderson** [comment]
To do

- [ ] Review regression test examples
- [ ] Draft sample test(s)
- [ ] Set up tests in excel for:

- Logging in a DQ filter user
- Logging in as an admin

- [ ] Add link to spreadsheet of tests when it is complete
