### ISSUE TITLE
Create confluence page documenting what needs to be done to update data assertion descriptions and field descriptions

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/DataQuality#117]
As an ALA data manager
I need to know where and how to update descriptions for data assertions and fields
So that they stay up to date

Requirements:
- Create confluence page (this is relevant to both the infrastructure project and the DQ project, so should probably be under the Operations heading in the main ALA team pages)
- Draw work flow diagram for updating data assertions
- If necessary draw separate diagram for field definitons
- Link to google doc spreadsheet and wiki in Github
- Link to field index in biocache interface
- Check if there is anywhere else these are seen

**Comment by M-Nicholls** [comment]
Page started here: https://confluence.csiro.au/display/ALASD/messages.properties+and+metadata

**Comment by M-Nicholls** [comment]
lots of useful content, as well as the flow charts I think a quick guide at the top would be helpful - numbered points with each step to update the metadata

e.g. 
Field descriptions:
1. draft and review field description
2. update/create wiki page https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki
3. update/create row in messages.properties https://github.com/AtlasOfLivingAustralia/biocache-service/blob/2c013e15d88350671ced5cabfe6781695d816fb9/src/main/webapp/WEB-INF/messages.properties (is this the right page and how to do this?)
4. deploy messages.properties (how to do this?)
5. check ... in production for updates

same for assertions
