### ISSUE TITLE
Record counts

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#120]
record counts not matching e.g. when filters are disabled: 89,551,375 records returned of 89,539,262  or 2071 records for spatially suspect but it's 2048 when the view exclude records is clicked

**Comment by hxuanyu** [comment]
Hi Miles, the total record number from production server https://biocache.ala.org.au/occurrences/search?taxa= is **89,551,375**

On test server when I disabled all I got **89,551,375** records returned of **89,551,375** which is correct.

Spatially suspect number 2048 (89551375 - 89549327 = 2048) is also correct.

<img width="1343" alt="Screen Shot 2020-07-22 at 12 54 40 pm" src="https://user-images.githubusercontent.com/6880129/88130470-fed96780-cc1d-11ea-8926-d724e14321ca.png">
<img width="709" alt="Screen Shot 2020-07-22 at 12 54 58 pm" src="https://user-images.githubusercontent.com/6880129/88130476-039e1b80-cc1e-11ea-9d24-b8db817b193b.png">

The total record number, excluded number are cached for 1 day. They can be cleared from admin page
<img width="1029" alt="Screen Shot 2020-07-22 at 1 20 59 pm" src="https://user-images.githubusercontent.com/6880129/88130688-88893500-cc1e-11ea-8742-caa9db9727f8.png">

I'll keep trying to see if I can reproduce them.

**Comment by M-Nicholls** [comment]
download - return to search results produces an error: https://biocache-dq-test.ala.org.au/occurrences/search?q=*%3A*&fq=%5Bspecies_group%3A%22Amphibians%22%2C+occurrence_decade_i%3A%221960%22%2C+family%3A%22Hylidae%22%5D&qualityProfile=Default

**Comment by M-Nicholls** [comment]
some examples - 
disable all filters, 
89,558,083 records returned of 89,551,375 for [all records]    

![image](https://user-images.githubusercontent.com/9424545/88235290-e6208e80-ccbd-11ea-8e6c-f77462d66126.png)

select the CSDM filter and then view the excluded records: https://biocache-dq-test.ala.org.au/occurrences/search?q=*%3A*&qualityProfile=CSDM&disableAllQualityFilters=true&fq=year%3A%5B*+TO+1970%5D+duplicate_status%3AD+geospatial_kosher%3Afalse+outlier_layer_count%3A%5B3+TO+*%5D

 4,605,164 records returned of 4,605,164 for [all records]    but the profile indicates that Data Quality Filters:
CSDM 7,263,827 records excluded

**Comment by M-Nicholls** [comment]
when a filter group is popped out the total number of records changes but the label doesn't - 

e.g. for default profile - pop out data quality

![image](https://user-images.githubusercontent.com/9424545/88236711-fb4aec80-ccc0-11ea-95c5-232706c35cbc.png)

the record count is correct but the label needs to indicate the user queries as in current production:

![image](https://user-images.githubusercontent.com/9424545/88236795-30573f00-ccc1-11ea-9f27-9613a0149b33.png)

**Comment by hxuanyu** [comment]
> some examples -
> disable all filters,
> 89,558,083 records returned of 89,551,375 for [all records]

----- I can confirm this. I was able to reproduce it on test server. The production server returns **89,558,083**. My local machine returned same number after cache disabled. I cleared cache from test server admin console then the wrong number was gone.

> 
> select the CSDM filter and then view the excluded records: https://biocache-dq-test.ala.org.au/occurrences/search?q=*%3A*&qualityProfile=CSDM&disableAllQualityFilters=true&fq=year%3A%5B*+TO+1970%5D+duplicate_status%3AD+geospatial_kosher%3Afalse+outlier_layer_count%3A%5B3+TO+*%5D
> 
> 4,605,164 records returned of 4,605,164 for [all records] but the profile indicates that Data Quality Filters:
> CSDM 7,263,827 records excluded

----- I was able to reproduce it on both test and local machine. Seems not a cache issue.

**Comment by hxuanyu** [comment]
As for the CSDM, 82,294,256 is total returned so **7,263,827** excluded is correct.

But the inverse is not correctly constructed. The inverse link is https://biocache-dq-test.ala.org.au/occurrences/search?taxa=&qualityProfile=CSDM&disableAllQualityFilters=true&fq=year:[*+TO+1970]+duplicate_status:D+geospatial_kosher:false+outlier_layer_count:[3+TO+*]

If connect the conditions with OR it returns the 
<img width="813" alt="Screen Shot 2020-07-23 at 10 16 48 am" src="https://user-images.githubusercontent.com/6880129/88241525-aeb9de00-cccd-11ea-9927-c18a46c70ef4.png">
correct number.

**Comment by alexhuang091** [comment]
Merge request created https://github.com/AtlasOfLivingAustralia/biocache-service/issues/490

**Comment by alexhuang091** [comment]
CSDM excluded works now

<img width="503" alt="Screen Shot 2020-08-06 at 10 57 21 am" src="https://user-images.githubusercontent.com/61677987/89478600-ca47dd00-d7d3-11ea-9057-88bda300ca45.png">
<img width="826" alt="Screen Shot 2020-08-06 at 10 57 35 am" src="https://user-images.githubusercontent.com/61677987/89478632-dfbd0700-d7d3-11ea-9904-9f5645d41341.png">
