### ISSUE TITLE
DQ filter UI additional features and bugs 

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#121]
select/de-select all filter groups button - distinct from disable filters, so a user can disable all the filter groups and just select a couple -(it's very slow to disable them one at a time for a large filter set) moved to: https://github.com/AtlasOfLivingAustralia/DataQuality/issues/126

user/DQ filter interactions indications - e.g. when using the same field the fields should be coloured and and have a mouse over. - needs better labeling around assertions  - it's not clear why the scientific name quality filter would interact with a location quality filter - it's the use of the assertions field in both. 
The mouse over on the user selected filter should indicate the field e.g. "This filter may conflict with these default quality filters: [filter group name] as they both use [field name]. Click to remove this filter" moved to https://github.com/AtlasOfLivingAustralia/DataQuality/issues/127

On the search results screen, mousing over the (i) icon for a filter category shows the filter query. This isn't very meaningful for a non technical person, clicking on the icon and getting the more detailed information makes more sense. I'd suggest changing the displayed mouseover text to: "Click for information" or something similar. moved to https://github.com/AtlasOfLivingAustralia/DataQuality/issues/128

**Comment by M-Nicholls** [comment]
Downloads email:

"Also cite the contributing data providers which are listed in the included "citation.csv" file. More information can be found at citing the ALA. "

citing the ALA link to go directly to:https://support.ala.org.au/support/solutions/articles/6000195866-how-to-cite-the-ala rather than the current redirect from  https://www.ala.org.au/about-the-atlas/terms-of-use/citing-the-atlas/

**Comment by RobinaSanderson** [comment]
Minor enhancement that only affects admin:
When you are adding a filter to a filter category, if you forget to add a description and save, the entire filter information is removed and you get an error that you need to have something in the description field. You then have to enter the whole thing again.
It would be better to get the error but the values are saved so you just have to enter the description rathe than the whole thing.
OR
Reorder the columns so the Description field is at the end of the row rather than the beginning so you have added the field or assertion, then you add the description in a left to right flow.

**Comment by M-Nicholls** [comment]
error when viewing excluded records for reusable records: https://biocache-dq-test.ala.org.au/occurrences/search?q=*%3A*&qualityProfile=re-usable#tab_mapView

**Comment by M-Nicholls** [comment]
error when interacting (e.g. adding user filters) with the open licensed data profile: Error from server at http://aws-sc7b.ala:8983/solr/biocache: org.apache.solr.search.SyntaxError: Cannot parse 'license:CC\-BY\-NC\ license\:CC\-BY\-NC\ 4.0\ \(Int\)\ license\:CC\-BY\-NC\ 3.0\ \(Aus\)\ license\:Creative\ Commons\ \-\ license\ at\ record\ level\ license\:CC\-BY\-NC\-SA\ 4.0\ \(Int\)\ license\:CC\-BY\-NC\-ND\ 4.0\ \(Int\)\ license\:other\ license\:CC\-BY\-SA\ 4.0\ \(Int\)\ license\:CC\-BY\-NC\ 3.0\ \(Au\)\ license\:CC\ BY\-NC\-Int\ license\:CC\-BY\-NC\-Int\ license\:Custom\ license\:CC\-BY\-NC\ 2.5\ \(Int\)\ license\:CC\-BY\-NC\-Aus\ license\:CC\-BY\-ND\ 4.0\ \(Int)': Encountered " ")" ") "" at line 1, column 474. Was expecting one of: <EOF> <AND> ... <OR> ... <NOT> ... "+" ... "-" ... <BAREOPER> ... "(" ... "*" ... "^" ... <QUOTED> ... <TERM> ... <FUZZY_SLOP> ... <PREFIXTERM> ... <WILDTERM> ... <REGEXPTERM> ... "[" ... "{" ... <LPARAMS> ... "filter(" ... <NUMBER> ...

**Comment by M-Nicholls** [comment]
All components moved to individual tickets
