### ISSUE TITLE
DQ filters applied to data transferred to Spatial

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#132]
Part 2. 
moving search logic out of hubs and into biocache service search interface 
add additional config to biocache-service to allow it to default to using default profile or disable
tidy up
so spatial can just be given parameters to use DQ filters and profile
User should know that the DQ filters have been applied

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/biocache-service/review/BS-CR-4
https://upsource.ala.org.au/downloads-plugin/review/DP-CR-5
https://upsource.ala.org.au/biocache-hubs/review/BH-CR-49

**Comment by M-Nicholls** [comment]
Also remove the "filters not applied" dialogue when this is working

**Comment by M-Nicholls** [comment]
record counts in info dialogue for the layer needs to be updated
check downloads

**Comment by M-Nicholls** [comment]
looking good, although disabling the data profiles isn't carrying through to the spatial portal - the most recent data profile is still applied
