### ISSUE TITLE
UI - Filter category descriptions and filters descriptions consistency

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/DataQuality#136]
As someone searching for occurrence records
I want to see consistent descriptions of the filters I am applying 
So that I understand the records that will be filtered out and have confidence in the results.

Current situation:
1. When I open the **Info** dialogue box for a profile, it is neatly arranged with it's description, category sections with category descriptions and filter tables with filter descriptions
![image](https://user-images.githubusercontent.com/23368496/89006731-bbcc7200-d34a-11ea-9e0b-3ddfbc8e13a8.png)
2. When I click on the (i) icon for a category of filters the description is populated from a concatenation of the individual filters which in larger categories like "Location" looks messy. The description entered for the filter category itself is not displayed.
![image](https://user-images.githubusercontent.com/23368496/89008016-3b5b4080-d34d-11ea-81b0-03685591d07b.png)
3. In addition, the information on this dialogue provides the description for the field used to hold the assertions, rather than the descriptions for the individual assertions. This is inconsistent with the Profile information dialogue and doesn't provide the user with the same amount of detail.
This image shows the information displayed for each assertion in the Profiles Info box for Location:
![image](https://user-images.githubusercontent.com/23368496/89008562-3b0f7500-d34e-11ea-8e07-25fb28ef87aa.png)

4. Finally, it would be good to provide a wiki link for geospatial kosher within either the category or the field description. The link could be to the ala-DataQuality wiki page https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/geospatial_kosher
or a direct link to the KB article explaining the fieldhttps://support.ala.org.au/support/solutions/articles/6000236981-what-does-the-spatially-valid-flag-geospatial-kosher-mean-

**Comment by M-Nicholls** [comment]
covered in https://github.com/AtlasOfLivingAustralia/DataQuality/issues/171
