### ISSUE TITLE
Expand icon should be on left side

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/DataQuality#138]
The expand/hide icon for the active DQ filters is currently on the far right side and is not only hard to notice but is also inconsistent with the similar icon for the facets on the left. See the green boxes below:

![image](https://user-images.githubusercontent.com/532845/89369489-944a2080-d721-11ea-9e5a-ece2aa6c325f.png)

I suggest the icon is moved to the left side (to the left of the text). 
In addition, the text and icon should be clickable, so it works the same way as the facet headings do (colouring should also be consistent - black icon colour and text in link colour).

**Comment by peggynewman** [comment]
Seems to be resolved.
