### ISSUE TITLE
Additional metadata entries - write description and wiki

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#140]
user_assertions
year
duplicate_record
license

need full metadata set up - write description and wiki page

**Comment by RobinaSanderson** [comment]
Draft text for user_assertions field. Headings taken from Wiki format:

Short description
Lists the current state of any user assertions raised by ALA end users or data providers about an occurrence record.

Description
Lists the current state of any user assertions raised by ALA end users or data providers about an occurrence record.

User assertions are stored as codes. See "ALA usage" below for interpretation of codes.

Relevant standards
None.

Expert vocabulary
None.

ALA usage
The following codes are used by the ALA:
Code 50001 = Open issue
Code 50002 = Verified
Code 50003 = Corrected
Code 50004 = No assertions
Code 50005 = Unconfirmed

Technical description,provenance, code
Code to meaning mapping is held in the messages.properties file<link>

**Comment by RobinaSanderson** [comment]
Draft text for year field. Headings taken from Wiki format:

Short description
The year in which an occurrence was observed.

Description
The year in which an occurrence was observed.

The ALA provides access to all records where a date, scientific name and location are given. However, occurrence records with a year value prior to 1700 should be treated carefully as identification is likely to have been retrospectively applied. 

Invalid year values, for example, a year in the future, will be flagged with a data quality assertion.

In some cases occurrence records have been provided without a year value, these are populated with a year value of "Not Supplied".

Relevant standards

Expert vocabulary

ALA usage



Technical description,provenance, code

**Comment by RobinaSanderson** [comment]
Draft text for duplicate_record field. Headings taken from Wiki format:

Short description
This field is used to identify possible duplicate records associated with this record. The ALA attempts to find the most complete record in a set of duplicates and identifies it as the _representative_ record.

Description
This field is used to identify possible duplicate records associated with this record. The ALA attempts to find the most complete record in a set of duplicates and identifies it as the _principal occurrence_ or  _representative_ record.

The ALA uses the following working definition for duplicate records:

_The principal occurrence is one preserved specimen, or observation of a taxon by a collector
or observer at a date and location. The principle record will have the most precise rendering
of these attributes.

Duplicate occurrences are additional specimens, preparations, observations or other related
material, of the same taxon at the same date and location by the same collector or observer._

Further information about the way the ALA identifies and references duplicates can be found at: https://drive.google.com/file/d/0B7rqu1P0r1N0N09VSm1Qbk5mMUk/view

Relevant standards
None.

Expert vocabulary
None.

ALA usage


Technical description,provenance, code

**Comment by RobinaSanderson** [comment]
Draft test for license field. Headings taken from Wiki format:

Short description


Description


Relevant standards

Expert vocabulary

ALA usage

Technical description,provenance, code

**Comment by RobinaSanderson** [comment]
Hi @M-Nicholls  - when I looked at the ALA usage for the licenses, I found the following values that don't map to CC-BY or CC-NC do you want me to add explanations for them?

used this query: https://biocache.ala.org.au/ws/occurrences/search?q=*%3A*&facets=license&pageSize=0&flimit=1000

CC0  records =19749470 (I assume this means open use)
Novalue records=4689402 (same as above)
Custom records=1198 (individual license?)
Other records=27245 (individual license?)
PDM records=2555 (no idea what this would be?)
CC-BY-NC-SA records=77734 (assume this is Non commercial and share alike)
CC-BY-ND records=1450 (no derivatives)
CC-BY-NC-ND records=28043 (non commercial no derivatives)
license at record level records=156497 (need to look at each record's metadata to determine license)

**Comment by RobinaSanderson** [comment]
Hi @M-Nicholls - I've had a go at the outstanding license descriptions. I don't think creative commons is a standard per se, but happy to list it as a standard if you think it is.

**Comment by M-Nicholls** [comment]
Hi @RobinaSanderson, I've edited a couple of the descriptions on the licenses (SA is a bit confusing at times) and added code links.  I'm waiting on a suggested code reference for user assertions

**Comment by M-Nicholls** [comment]
Wiki pages created:

https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/user_assertions
https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/assertions
https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/year
https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/license

**Comment by RobinaSanderson** [comment]
Hi Miles

For "Year" I've added in a brief description and link to ISO 86901 under "Standard".
I made minor formatting changes to the others. All good to go now, I think.
