### ISSUE TITLE
Updated Information and actions dialogue

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#150]
remove the pop-out icon (will be put into the info dialogue)
change the mouse over text on the filter group (i) to "click for more information and actions"

Update the filter group information dialogue:
at the bottom of the dialogue under the table add a  section "Actions" with a "Split filter" button with the current mouse over text

**Comment by alexhuang091** [comment]
Hi Miles, the changes I've made is to add the action button into the dialog footer area:

<img width="632" alt="截屏2020-09-07 上午9 04 26" src="https://user-images.githubusercontent.com/61677987/92336983-8fdea200-f0e9-11ea-9e38-5aab05c377bd.png">

It's similar to the actions in the facets selection:
<img width="626" alt="截屏2020-09-07 上午9 07 54" src="https://user-images.githubusercontent.com/61677987/92337012-d6cc9780-f0e9-11ea-88e0-398689e2dc7d.png">

Let me know if you are happy with that or I need to move it out of the footer to a section directly under the table as described.

**Comment by M-Nicholls** [comment]
done as described except for an "Actions" title for the new section but we'll set that up in a new issue
