### ISSUE TITLE
Update outliers field metadata

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#152]
fix the typo in the outliers field description - https://github.com/AtlasOfLivingAustralia/DataQuality/issues/142
general explanation in intro to Outliers description

Didn't understand what the outlier_count meant

**Comment by Tasilee** [comment]
Outlier count: I presume it is how many of the 5 environmental layers the record is an outlier on, with possible values of 0,1,2,3,4 or 5.
