### ISSUE TITLE
DOI page information updates for DQ filtered data downloads

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#153]
Differentiate user filters from DQ filters

It's difficult to work out whether a data profile was used or if it was disabled and what the parameters and URL do:

Rename “search query” to “Parameters to re-run query with current data”
“Search URL” rename to “Search URL to re-run query with current data”, add a line underneath for spacing
Data Quality Filters section – rename to data profile, add profile name or profiles disabled

**Comment by alexhuang091** [comment]
<img width="1185" alt="Screen Shot 2020-10-13 at 9 58 44 am" src="https://user-images.githubusercontent.com/61677987/95797245-bc19be00-0d3a-11eb-96a0-9bbc9f9caac8.png">

Hi Miles, you mean change it to 

Data profile: ALA
Filters:
Name     Filter
xxxx        xxxxx
yyyy        yyyy 


and what's  
> or profiles disabled
