### ISSUE TITLE
Updates to metadata confluence page

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#164]
Metadata confluence page : https://confluence.csiro.au/display/ALASD/Field+and+assertions+metadata+architecture+and+editing

a quick guide at the top would be helpful - numbered points with each step to update the metadata
e.g.
Field descriptions:
1.	draft and review field description
2.	update/create wiki page https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki
3.	update/create row in messages.properties https://github.com/AtlasOfLivingAustralia/biocache-service/blob/2c013e15d88350671ced5cabfe6781695d816fb9/src/main/webapp/WEB-INF/messages.properties (is this the right page and how to do this?)
4.	deploy messages.properties (how to do this?)
5.	check ... in production for updates
same for assertions

**Comment by RobinaSanderson** [comment]
I've updated the page: https://confluence.csiro.au/display/ALASD/Field+and+assertions+metadata+architecture+and+editing
