### ISSUE TITLE
Filter group info dialogue updates 2

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#171]
Remove "quality filters" from the end of the title e.g. Just show "Exclude records with additional spatial quality issues"

For consistency with profile info dialogue, add the description from admin under the title:

"Exclude records with location related data quality assertions"

Change action buttons to red text (consistent with other buttons)

Put "View excluded records" under the excluded record count:

125,695 records are excluded by this category

View excluded records (in red)

then:

Filter applied: fq=-assertions:"habitatMismatch"  AND -assertions:"occCultivatedEscapee"  AND -assertions:"zeroLatitude"  AND -assertions:"zeroLongitude"  AND -assertions:"invertedCoordinates"  AND -assertions:"coordinatesCentreOfStateProvince"  AND -assertions:"coordinatesCentreOfCountry" 

*add a "click for more information" mouse over on the (?) icons in the section above
Expand filters (in red)

remove the current Description field

![Filter group info dialogue v2](https://user-images.githubusercontent.com/9424545/93966467-27a9e480-fda8-11ea-8387-18d275db3939.jpg)

**Comment by alexhuang091** [comment]
> Filter applied: fq=-assertions:"habitatMismatch" AND -assertions:"occCultivatedEscapee" AND -assertions:"zeroLatitude" AND -assertions:"zeroLongitude" AND -assertions:"invertedCoordinates" AND -assertions:"coordinatesCentreOfStateProvince" AND -assertions:"coordinatesCentreOfCountry"
> 
> *add a "click for more information" mouse over on the (?) icons in the section above


Hi Miles, you mean an (?) appended at the end so it's `Filter applied: fq = xxxxxx (?)`? What to do when clicked?
