### ISSUE TITLE
change "wiki" to "info" in information dialogues

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#178]
change "wiki" to "info" in information dialogues - profile info dialogue and filter group dialogues

**Comment by alexhuang091** [comment]
Hi Miles, is it to change the column name to 'Info' like this
![image](https://user-images.githubusercontent.com/61677987/95923104-7de6d200-0e00-11eb-8fd9-4f04acc72c90.png)

**Comment by M-Nicholls** [comment]
"Further information" as the column header
"Link" as the field content

**Comment by M-Nicholls** [comment]
In the filter group info dialogue the filter description table still has "wiki" as the link text:


Filter description | Filter value | Further information
-- | -- | --
Exclude  all records with an assertion of A marine species detected in a  terrestrial environment or a terrestrial species detected in a marine  environment. | -assertions:"habitatMismatch" | Wiki
