### ISSUE TITLE
Add info pop up frst time a user sees the data profiles interface

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#180]
info popup with "don't show this again" options

short explanation of data profiles and link to support aricles

**Comment by M-Nicholls** [comment]
![new data profiles dialogue](https://user-images.githubusercontent.com/9424545/96395561-ad3a7c00-1210-11eb-90db-9278d71a112a.jpg)

**Comment by alexhuang091** [comment]
Hi Miles, 

Do we need a checkbox, labeled as 'don't show it again'.

If checked then never show it. If not, we still show it next time ?

**Comment by alexhuang091** [comment]
or the pop up only shows the first time.

**Comment by alexhuang091** [comment]
Seems only show it first time will be a better idea. Otherwise everytime when result returns and page refreshes user sees the dialog again and again.

**Comment by M-Nicholls** [comment]
I'd agree - just show the first time

**Comment by M-Nicholls** [comment]
Text correction: add "do" (not bolded on the dialogue) to the first line

Search results are now filtered by default to exclude records that **do** not fit a particular profile.

Information on the profiles and the filters used in each profile is available via the  icons.
