### ISSUE TITLE
Add duplicate assertion type to flag an issue

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#187]
add duplicate as a flag an issue type
add field for duplicate record ID - copy and paste the URL for the other record (could have a button on a record details page "copy record ID") - this is the representative record
indicate duplicate type - same occurrence, tissue sample, split specimen.
one record has to be nominated as representative and one as duplicate - the one that's being flagged is the duplicate the other is representative

and storing information

**Comment by M-Nicholls** [comment]
note to also accommodate the herbarium definition of a "duplicate" - ie. the same plant cut into bits and sent to different herbaria for storage

**Comment by M-Nicholls** [comment]
currently "R" representative and "D" for Duplicate
add new types to the indexing so that they are searchable

**Comment by M-Nicholls** [comment]
UI needs to display differently for the duplicate assertion
validate record URL provided

- just check record exists

store info

**Comment by M-Nicholls** [comment]
review model approach with other Dev's

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/biocache-hubs/review/BH-CR-55
https://upsource.ala.org.au/biocache-service/review/BS-CR-5
https://upsource.ala.org.au/biocache-store/review/BS-CR-16

**Comment by M-Nicholls** [comment]
is this setting a user_assertion status? if so it will be filtering out records in the ALA general profile (should be ok, just so we're aware of it)
