### ISSUE TITLE
Add a link to manage your personal data profile to My profile

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#221]
Add a "Manage my personal data profile" link to My profile - so users can get to the data profiles admin screen

**Comment by alexhuang091** [comment]
Hi Miles, would you like me to add the separator to separate the profiles and 'disable data profiles'

And also _Add a "Manage my personal data profile" link to My profile_ - where is 'My profile' ?

<img width="570" alt="Screen Shot 2021-02-02 at 1 46 02 pm" src="https://user-images.githubusercontent.com/61677987/106545240-24e0ac80-655d-11eb-9870-1a9df5925a26.png">

**Comment by M-Nicholls** [comment]
use the text: "Manage your personal data quality filters for occurrence records" for the link on the My Profile page

**Comment by M-Nicholls** [comment]
added to https://github.com/AtlasOfLivingAustralia/DataQuality/issues/215
