### ISSUE TITLE
Create a data profile from the current query

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#223]
Create a data profile based on the query the user is currently using in the biocache

generate a filter group based on the user parameters
populate the filter descriptions
present a view for the user to review, edit and accept

If a data profile is active then copy the profile and add any new parameters

**Comment by alexhuang091** [comment]
Hi Miles, several questions.

1. When the user clicks the 'save', ask him to login, same as the 'flag an issue' does.
2. No matter admin or normal user, always save as a private profile? (it depends on point 3)
3. after user logged in and clicks 'save', should we pop up a dialog asking him to input profile name and shortname (the similar dialog as we create a profile in dq-admin) ? if yes, we may have a checkbox group to select private or public.  Or we can create a unique name automatically. like savedprofile-0702-2021-1.
4. If save as private selected but user already has a private profile, how?
5. What to do once save succeeds? reload the page with the saved profile selected? so the long URL just changed to &qualityProfile=saveprofilename

**Comment by M-Nicholls** [comment]
transferred to https://github.com/AtlasOfLivingAustralia/DataQuality/issues/215
