### ISSUE TITLE
Profile admin error messages

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#225]
Tidy up error messages for users:

Errors when importing
•  Property [shortName] of class [class au.org.ala.dataqualityfilter.QualityProfile] with value [ALA] must be unique
•  Property [name] of class [class au.org.ala.dataqualityfilter.QualityProfile] with value [ALA General] must be unique

Create profile
If no short name – error – don’t allow save w/o one

Create category 
– no short name – error- don’t allow save w/o one

Add filter
Screen layout – text is cut off in fields
If try to generate a description for duplicate_record – pop up with data-quality-service-tes.ala.org.au says: No description found – improve error message

**Comment by alexhuang091** [comment]
Import error has been changed to this:

<img width="1219" alt="截屏2021-02-01 上午11 58 35" src="https://user-images.githubusercontent.com/61677987/106403902-e2e43780-6484-11eb-8209-7413f3637d7d.png">

**Comment by alexhuang091** [comment]
Hi Miles,

> Add filter
> Screen layout – text is cut off in fields

Could you give a screenshot which part is cut off?

> If try to generate a description for duplicate_record – pop up with data-quality-service-tes.ala.org.au says: No description found – improve error message

Change to 'No description found for field xxxx' ? or try to remove the 'data-quality-service-tes.ala.org.au says' ?

**Comment by M-Nicholls** [comment]
Change the error message to"No description found for field: xxxx"

Also need to update the field description so there is one - "Possible duplicate records associated with this record"

**Comment by qifeng-bai** [comment]
Solved
