### ISSUE TITLE
Data profiles settings fixes

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#230]
When settings are "collapsed" if the user open the details they should remain open unless reset e.g. settings are set to "collapsed" and the user expands the details, they disable a filter group, the details collapse again - they should remain open unless "reset" or the user clicks collapse

**Comment by M-Nicholls** [comment]
settings dialogue to show the current user settings when opened.
may be intermittent...

e.g. settings set to CSDM and collapsed, when opening settings dialogue it shows ALA general and collapsed

**Comment by M-Nicholls** [comment]
expanded/collapsed is sticking between sessions

select expanded in settings
collapse manually
close the browser window
open a new browser window
run any biocache query - UI shows data profiles collapsed

when opening a new window it should default back to the default settings

**Comment by alexhuang091** [comment]
> expanded/collapsed is sticking between sessions
> 
> select expanded in settings
> collapse manually
> close the browser window
> open a new browser window
> run any biocache query - UI shows data profiles collapsed
> 
> when opening a new window it should default back to the default settings

I'll have a look Miles. Does it happen every time? Is it possible 1 session is logged in and the other is logged out?

**Comment by alexhuang091** [comment]
> when opening a new window it should default back to the default settings

Hi Miles, please use https://auth-test.ala.org.au/userdetails/property/getProperty?alaId=56528&name=null.hub_charts.dqUserProfile  to check if the user settings is saved successfully before opening a new window.

And make sure it's a new window not a new tab. On my machine tabs shares the cookie so it's sticky among tabs.
