### ISSUE TITLE
view all records excluded by a profile

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#235]
user feedback 

Is there a way to simply see all the records with data quality issues. You can opt out of showing flagged records, but can you see them all as a set with one click? if not, again, this would be useful for those doing data quality checking. Some records will always remain suspect, but some errors can be corrected in the original data sets, thus reducing the number of suspect records.

add the sections from the filter group dialogue to the profile info dialogue, above "Filter categories"

 # records are excluded by this category
View excluded records

**Comment by qifeng-bai** [comment]
'Excludes options' has been added
