### ISSUE TITLE
Rename "Data profile" to results pre-filter

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#236]
in top nav update "Data profile" to
Results are pre-filtered for: [filter set name (dropdown)]
and if disabled
Results pre-filters are: [Disabled (dropdown)]

in left hand Nav
update "Data profile" to "Results pre-filter"

in settings dialogue
"Data profile user settings" to "Results pre-filter user settings"

Your default results pre-filter is applied to searches unless you select another pre-filter from the results pre-filter drop down

Defaults profile to "Default results pre-filter"
Show data profile details to "Show results pre-filter details"

**Comment by M-Nicholls** [comment]
Update names of results pre-filter sets

update pre-filter names to fit with UI label changes
ALA General - General Data Quality
CSDM - Species distribution modelling (CSDM)
licensing - ok as is

**Comment by M-Nicholls** [comment]
Update results pre-filtering labels in support material

update previous blogs and other comms
update screen shots
replace data profile with "Results pre-filtered for:"
or "occurrence search results pre-filter" as needed

**Comment by qifeng-bai** [comment]
Solved
