### ISSUE TITLE
Bug - excluded record counts when &fq=geospatial_kosher%3Atrue

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#239]
reported by user when moving from explore your area the geospatial_kosher=true flag is added to the URL and it results in incorrect excluded record counts

reported for this URL https://biocache.ala.org.au/occurrence/search?q=*%3A*&lat=-26.5617&qualityProfile=ALA&lon=148.7929&radius=5&fq=geospatial_kosher%3Atrue#tab_mapView

the inclusion of "&fq=geospatial_kosher%3Atrue"seems to cause the issue e.g. https://biocache.ala.org.au/occurrence/search?q=*%3A*&fq=geospatial_kosher%3Atrue#tab_mapView has the problem 
while 
https://biocache.ala.org.au/occurrence/search?q=*%3A*#tab_mapView does not.

verified on Chrome, edge and IE, seemed ok on firefox

![image](https://user-images.githubusercontent.com/9424545/119751135-f0af4400-bedd-11eb-8822-cf7e1b8a71f6.png)

**Comment by peggynewman** [comment]
Using spatiallyValid returns a better count for excluded records:
https://biocache.ala.org.au/occurrence/search?q=*%3A*&lat=-26.5617&qualityProfile=ALA&lon=148.7929&radius=5&fq=spatiallyValid%3Atrue#tab_mapView

**Comment by qifeng-bai** [comment]
72,285,450 records returned of 4,277 for [all records]   when fq=geospatial_kosher is used
