### ISSUE TITLE
Bug - dots on the map not correct for query and data filter

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#240]
records for the Eastern Grey Kangaroo https://biocache.ala.org.au/occurrence/search?taxa=Macropus+giganteus&qualityProfile=ALA#tab_mapView

A few questions:
1.	With the ALA general filter ON, in map view, there are some dots I can't click on (e.g. the dot in New Zealand, the dot in the water off NSW, one of the dots near Alice Springs) The waiting indicator just spins but doesn't return anything. If I disable the filters, I can click on the dot and get to the record. 
Question 1 - why can I even see the dot still on the map? 
2.	If I turn off just the "Exclude spatially suspect records" filter, those 3 dots now disappear from the map. 
Question 2 - shouldn't it work the other way around? The dots should not appear when the filter is ON (exclude those points) and only appear when the filter is OFF (include those points)?

**Comment by M-Nicholls** [comment]
Species in question is: Anthochaera phrygia (the Regent Honeyeater)
Query in Biocache: https://biocache.ala.org.au/occurrence/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3A83225d29-264f-4236-9dda-32f7d60fb3af&qualityProfile=ALA#tab_mapView
with ALA General profile enabled

Issue 1. DQ filter works the wrong way around. 
•	try to click on the dot on the map in central Queensland just north of the NSW border. It just gives a spinny wheel but won't open the record.
•	Note that filter "exclude spatially suspect records" shows no records excluded
•	Turn that filter to OFF (uncheck the box) and the record disappears from the map display. 
•	Still shows that zero records are excluded but the record is gone
•	The behaviour I would expect is that this record is flagged as Spatially Suspect and is excluded with the filter turned on (not off)

**Comment by qifeng-bai** [comment]
Solved

**Comment by nickdos** [comment]
Can you please explain why/how this is solved? I can't see a commit that might've "solved" the issue...
