### ISSUE TITLE
Increase the number of trusted records...

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#246]
### ...so that the trusted data set is larger

positive annotation - user feedback of this record is good

Edit lower quality records to bring them up to inclusion standards

Incomplete - send back to the custodian

Invalid
unreadable - send back to custodian
out of range - calculate new value

Incorrect
Manual detection - User suggested correction

Automated detection - 
Duplicate - only show a single record
Not authoritative - improve where possible, request additional information
Not fit for purpose - precision attributes may be able to be improved

**Comment by M-Nicholls** [comment]
make report on the quality of a data set so that the owners can improve their data for inclusion

**Comment by M-Nicholls** [comment]
manually updating records must be coupled with an audit trail

**Comment by peggynewman** [comment]
These ideas are captured elsewhere. - closing.
