### ISSUE TITLE
Indicate what purposes the records in a data set are suitable for

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#261]
rather than using the DQ assertions to determine whether to use record(s) or data set(s) - document what the data set should be used for e.g.

by the owner:
collected for (primary purpose)
Suitable for (likely to be useful for...)

by users:
user notes - I found this to be suitable for...
caveats and usage notes - when using this data for... I had to ...

**Comment by M-Nicholls** [comment]
Add two fields to the data resource page:
Collected for:
Suitable for:

with a configurable drop down list of analysis types including:
•	Species list national | state | >1000km radius | 100-1000km radius | 10k to 100km radius | <10km radius
•	Distribution modelling: types of distribution modelling
•	Abundance
•	Condition
•	Change over time
•	Others…?

**Comment by M-Nicholls** [comment]
Add the "suitable for" fields to the indexing and UI

**Comment by alexhuang091** [comment]
Hi Miles, in collectory we have

- `in` for institution
-  `dp` for data provider
-  `dr` for data resource
-  `co` for collection
-  `drt` for temp data resource
-  `dh` for data hub

I only need to change the `dr`?

**Comment by alexhuang091** [comment]
> Add two fields to the data resource page:
> Collected for:
> Suitable for:

Hi Miles, so now I'm adding these 2 fields into `dr`. Is it true that:
- their default values are empty, so when going to a data resource page, the dropdown list has nothing selected
- once the owner selects in the dropdown list, save them into database.

**Comment by M-Nicholls** [comment]
yes, only change the DR and yes, the default is empty and once selected save the value
this is also only an admin function

**Comment by alexhuang091** [comment]
Hi Miles, so we add the dropdown list somewhere in the `metadata` section?

![1](https://user-images.githubusercontent.com/61677987/141701255-1eb5af9f-d64a-4692-87e8-f9c4e69d7a85.jpg)

**Comment by alexhuang091** [comment]
Hi Miles, one thing need your help: to make all these configurable, I've put settings into the config file, it's like

```
collectedfor = {
    "mainuse":"first reason", 
    "secondreason": "second reason"
}
```

it's a list of key value pairs, the part after `:` will be shown to user and the part before `:` (`mainuse` or `secondreason`) will be saved into database.

So that in the future when we do filtering in solr, we don't need to use the long descriptive string, we can just use the short version. 

Could you provide me in this format the settings I should use for both collectedFor and usedFor (the keys and values)?

**Comment by M-Nicholls** [comment]
After talking with Martin what would work better is:

How the data was collected
Data collection protocol name: text field
Data collection protocol documentation: field to enter a URL

This data set is likely to be suitable for: [drop down]

types of analysis:

•	Species list national 
•	Species list state
•	Species list >1000km radius
•	Species list 100-1000km radius
•	Species list 10k to 100km radius
•	Species list <10km radius
•	Defining a species distribution 
•	Quantifying abundance at a point in time
•	Quantifying change over time
•	Other: text field

**Comment by peggynewman** [comment]
This appears to be in production. Closing.
