### ISSUE TITLE
Filter data on assertions

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#30]
**User Story:**

As a: Data User
I want: Default results filtered on quality assertions
So that: poor quality data is filtered out

**Acceptance Criteria:**

Given:I am on the ALA website and have queried the biocahce
When: My results are returned
Then:
the data is pre filtered on
Name.not.supplied=='true' (Lee: This won’t apply when there is a species focus) – no data
Name.not.recognised=='true' (Lee: This won’t apply when there is a species focus)
Cultivated...escapee=='true' (Lee: dwc:establishmentMeans /= “ “ or /= “native”)
 Unable.to.convert.UTM.coordinates=='true' (Lee: Can’t find info on this)
Supplied.coordinates.are.zero=='true' (Lee:OK)
Zero.latitude=='true' (Lee:OK)
Zero.longitude=='true' (Lee:OK)
Coordinates.centre.of.country=='true' (Lee:OK)
Supplied.coordinates.centre.of.state=='true' (Lee:OK)
processing.Error=='true' (Lee: This one still has me beat)
according to the facet query:
fq=-(assertions%3A%22nameNotRecognised%22%20OR%20assertions%3A%22invalidScientificName%22%20OR%20assertions%3A%22habitatMismatch%22%20OR%20assertions%3A%22occCultivatedEscapee%22%20OR%20assertions%3A%22zeroLongitude%22%20OR%20assertions%3A%22zeroLatitude%22%20OR%20assertions%3A%22zeroCoordinates%22%20OR%20assertions%3A%22invertedCoordinates%22%20OR%20assertions%3A%22coordinatesOutOfRange%22%20OR%20assertions%3A%22coordinatesCentreOfStateProvince%22%20OR%20assertions%3A%22coordinatesCentreOfCountry%22%20OR%20assertions%3A%22decimalLatLongCalculationFromEastingNorthingFailed%22%20OR%20assertions%3A%22decimalLatLongConversionFailed%22)

**Comment by RobinaSanderson** [comment]
I've implemented the following filters in the test environment:
![image](https://user-images.githubusercontent.com/23368496/87629880-28eedd80-c777-11ea-8041-b6dde767d8cc.png)
