### ISSUE TITLE
Filter data on outliers

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#35]
**User Story:**

As a: Data User
I want: Default results filtered on environmental and expert distribution outliers
So that: environmental and expert distribution outliers are excluded

**Acceptance Criteria:**

Given: I am on the ALA website and have queried 
When: My results are returned
Then:
the data is pre filtered on
Outlier layers – outlier for 3 layers
fq=-outlier_layer_count%3A%223%22
and
expert distribution outliers are excluded (needs investigation)

**Comment by M-Nicholls** [comment]
changed to a range query fq=-outlier_layer_count:[3 TO *] to include 4 and 5 outlier layer counts

the fields for expert distribution outlier aren't currently in the biocache - it looks like the process hasn't been run for a while:
from slack:

If I have found the correct job, it isn't setup to automatically run. It has only successfully been run once ever, by David Martin on 5 July 2019, and it took 47 hours to complete: http://aws-scjenkins.ala:9193/job/Outlier%20detection/job/Full%20Expert%20Distribution%20Outlier%20Detection/buildTimeTrend
1:03

Not familiar with how the solr schema is generated to know why the fields may not be present for it at this point. Do our regular "Complete Reprocess" jobs that we run once a week overwrite it?

I'll set up a new issue to look at the expert distribution outliers

**Comment by Tasilee** [comment]
Please also note https://github.com/AtlasOfLivingAustralia/spatial-service/issues/101

We will need to do this anyway given the review of the layers!!
