### ISSUE TITLE
apply DQ filter to queries directly on the API

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#59]

**Comment by ansell** [comment]
**If this is even being contemplated, the current solution for the config storage (#56) must be immediately revisited.** It is not a viable design to have biocache-service depending on biocache-hubs, which the current prototype solution for #56 has done. That would create a circular dependency.

**WARNING: This goal is also very high risk, and very high impact.** If this is chosen as a goal, all existing systems will need UX work to give users the opportunity to enable and disable filters as they see fit. While the data quality work is only being applied to biocache.ala.org.au, the effects could be limited through more intensive UX work and testing there. If biocache-service operations are being silently transformed by the current opt-out filters, there will be large effects on the rest of the ALA. 

The current UX model of individually opting-out of each of the current filters for each query is also not viable if ALA-wide changes are to be implemented. There will need to be a single switch to turn all of the silent data quality filters off permanently for those users who require to see raw data.
