### ISSUE TITLE
UI for DQ filters

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#73]
Clear up UI for DQ filters
![DQ filters results 2](https://user-images.githubusercontent.com/9424545/78743636-861e0a80-79a2-11ea-9191-9673e56f7e5b.jpg)

**Comment by M-Nicholls** [comment]
indicate to a user where a filter they have set is interacting with a DQ filter e.g. when a user sets an fq in the URL or coordinateUncertaintyInMeters the DQ filter needs to indicate the interaction

**Comment by sbearcsiro** [comment]
Note, we'll need to update the translations for "Selected filter" to "User selected filter"

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/biocache-hubs/review/BH-CR-18

**Comment by M-Nicholls** [comment]
testing notes:
UI looks great

https://biocache-dq-test.ala.org.au/occurrences/search?q=*%3A*
•	“pop out” filter
•	Re-enable filter (pop out button is set back to “pop out”)
•	“pop out” filter again
•	 “user selected filters” are duplicated, record counts are ok
Expected: when a filter is “popped out” the checkbox to re-enable it is disabled (same in the side facet nav for all functionality)

Pointer is an arrow over the (i) but not over the label - change to both an arrow (indication there is a mouse over)

Add “Filter applied fq=” to the (i) mouse over before the filter details 
e.g. "Filter applied: fq=-(geospatial_kosher:"false")&fq=-(assertions:"habitatMismatch")&fq=coordinate_uncertainty:[0+TO+10000]"

when a filter is disabled (by the checkbox) the "pop out" button should be disabled

**Comment by M-Nicholls** [comment]
the "pop-out" button on the left hand facets nav doesn't put the filters in the "User selected filters:" box
https://biocache-dq-test.ala.org.au/occurrences/search?q=*%3A*&disableQualityFilter=location 

Pointer is an arrow over the (i) but not over the label - change to both an arrow (indication there is a mouse over)

Add “Filter applied fq=” to the (i) mouse over before the filter details
e.g. "Filter applied: fq=-(geospatial_kosher:"false")&fq=-(assertions:"habitatMismatch")&fq=coordinate_uncertainty:[0+TO+10000]"

**Comment by M-Nicholls** [comment]
the facets on the left hand nav don't open when clicked so I can't test the pop-out.

mouse pointer change is good as is the "Filter applied fq=" text addition
