### ISSUE TITLE
see an indication that a user fq is interacting with a DQ filter

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#76]
indicate to a user where a filter they have set is interacting with a DQ filter e.g. when a user sets an fq in the URL or coordinateUncertaintyInMeters the DQ filter needs to indicate the interaction

**Comment by M-Nicholls** [comment]
indicate on DQ filter with red asterisk - mouse over text that "a user elected filter is interacting with this filter"

**Comment by M-Nicholls** [comment]
https://biocache-dq-test.ala.org.au/occurrences/search?q=*%3A*&fq=-%28geospatial_kosher%3A%22false%22%29&fq=-%28assertions%3A%22habitatMismatch%22%29&fq=coordinate_uncertainty%3A%5B0+TO+20000%5D

the red highlight is good and the mouse over text on the "user selected filter" is good, can we add the same text to the mouse over on the "Quality filters applied" section indicating the user filter that is affecting the DQ filter and provide the details of the filter being affected e.g. This filter may conflict with these default quality filters:[location, coordinate uncertainty (in metres): [0 TO 10000]

**Comment by M-Nicholls** [comment]
when looking a t this query and filters: https://biocache-dq-test.ala.org.au/occurrences/search?q=*%3A*&fq=-%28geospatial_kosher%3A%22false%22%29&fq=-%28assertions%3A%22habitatMismatch%22%29&fq=-assertions%3A%22nameNotRecognised%22&fq=-assertions%3A%22invalidScientificName%22&fq=-assertions%3A%22habitatMismatch%22&fq=-assertions%3A%22occCultivatedEscapee%22&fq=-assertions%3A%22zeroLongitude%22&fq=-assertions%3A%22zeroLatitude%22&fq=-assertions%3A%22zeroCoordinates%22&fq=-assertions%3A%22invertedCoordinates%22&fq=-assertions%3A%22coordinatesOutOfRange%22&fq=-assertions%3A%22coordinatesCentreOfStateProvince%22&fq=-assertions%3A%22coordinatesCentreOfCountry%22&fq=-assertions%3A%22decimalLatLongCalculationFromEastingNorthingFailed%22&fq=-assertions%3A%22decimalLatLongConversionFailed%22&disableQualityFilter=quality-assertions

the "invalid scientific name" user filter is showing that it has a conflict with the "location" DQ filter which shouldn't be the case

**Comment by alexhuang091** [comment]
Hi Miles,

DQ Location filter = fq=-(geospatial_kosher:"false") AND -(assertions:"habitatMismatch") AND -coordinate_uncertainty:[10000 TO *]

So any user filter with assertions:xxxx will conflict with it.


Thanks

**Comment by M-Nicholls** [comment]
ok, thanks Alex we may need to look at what fields are in the filters or at splitting up the assertions filters a bit differently but the functionality works as intended.
