### ISSUE TITLE
view  information on the fields used in the DQ filters

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#78]
display detailed metadata on the filters and fields:
clickable (i) opens a bootstrap modal that allows further interaction 
e.g. 
Filter applied: fq=-([geospatial_kosher] (tooltip):"false")&fq=-([assertions](tooltip):"habitatMismatch")&fq=[coordinate_uncertainty](tooltip):[0+TO+10000]

content of the tooltip is the description from the biocache fields web service

use the field list and metadata from the biocache (https://biocache.ala.org.au/fields) to look up the field description

**Comment by M-Nicholls** [comment]
use the field list in the admin tool when indicating the fields in the fq - split into https://github.com/AtlasOfLivingAustralia/DataQuality/issues/79

**Comment by M-Nicholls** [comment]
From @alexhuang091 

I’ve done some changes for the modal dialog.

From the webservice you can get field description and info. Info seems to be more informative

 
![image](https://user-images.githubusercontent.com/9424545/80157752-35e1b200-860a-11ea-80fe-4367a3a3e957.png)


Some have just an URL in info
 
![image](https://user-images.githubusercontent.com/9424545/80157763-3e39ed00-860a-11ea-88d8-b07c7ff21051.png)

The model looks like this (ignore the font and color now). Do you want to add a table under the fq so that each table row contains info of a filed?
This way user get the opportunity to click the link inside the info.

![image](https://user-images.githubusercontent.com/9424545/80157782-48f48200-860a-11ea-8492-38ff4ceaab1f.png)

**Comment by M-Nicholls** [comment]
Looking great, using the info field sounds correct and the links are to the field definition on the standard so that's correct but we'll need to add some text as well.

so the fq info should be: 
"Filter applied: fq=... list of filters" and then let's try the table below as you suggest.

**Comment by alexhuang091** [comment]
Hi Miles,

Do we need a table then? Each row for a field? Columns are field name, field description, field info?

**Comment by M-Nicholls** [comment]
yes, let's have a look at the table as you've described: Each row for a field, Columns are field name, field description, field info

**Comment by alexhuang091** [comment]
Sorry,

Previous email already said it. I’ll do the table.


Thanks

From: "HUANG, Alex (NCMI, Black Mountain)" <A.Huang@csiro.au>
Date: Friday, 24 April 2020 at 9:12 am
To: AtlasOfLivingAustralia/DataQuality <reply@reply.github.com>
Subject: Re: [AtlasOfLivingAustralia/DataQuality] view information on the fields used in the DQ filters (#78)

Hi Miles,

Do we need a table then? Each row for a field? Columns are field name, field description, field info?

**Comment by alexhuang091** [comment]
Let me know if you have any suggestions on this

<img width="601" alt="Screen Shot 2020-04-24 at 1 54 23 pm" src="https://user-images.githubusercontent.com/61677987/80173468-4eb28d80-8633-11ea-9760-a88bdd0da0b9.png">

**Comment by alexhuang091** [comment]
2 questions:

1. Do I need to translate the content? Filter name may can, but are the filter description and filter info from web service always in English?
2. The values (the part after :, in this case [1900 TO *], habitatMismatch, [0 TO 100000]) are translated by biocache-service and return back to front end. Should we also add a tooltip for the values?

**Comment by alexhuang091** [comment]
> 2 questions:
> 
> 2. The values (the part after :, in this case [1900 TO *], habitatMismatch, [0 TO 100000]) are translated by biocache-service and return back to front end. Should we also add a tooltip for the values?

I will not do this for now. Translation (display name) sometimes doesn't work seems. Especially when there is '-' or 'AND' in a fq.  

For example if `fq = occurrence_decade_i:["1900" TO *] AND -(assertions:"habitatMismatch") AND coordinate_uncertainty:["0" TO "10000"]` display (translated) name should be `Decade: [1900 TO *] AND [exclude] (assertions: "Habitat incorrect for species") AND Coordinate uncertainty (in metres): [0 TO 10000]
`

but actaully current biocache-serivce backend returns `Year (by decade): ["1900" TO *] AND -(assertions:"habitatMismatch") AND coordinate_uncertainty:["0" TO "10000"]`

**Comment by alexhuang091** [comment]
> 1. Do I need to translate the content? Filter name may can, but are the filter description and filter info from web service always in English?

Only the 'Filter name' may possibly already be translated. 'Description' and 'Info' are never translated so they always in English.

Thus there's no need to do translation.

**Comment by M-Nicholls** [comment]
looks good - additional info on filter values added as new issue (https://github.com/AtlasOfLivingAustralia/DataQuality/issues/84)
