### ISSUE TITLE
use the field list in the admin tool when indicating the fields in the fq

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#79]
on the filter admin screen (https://biocache-dq-test.ala.org.au/admin/dataQualityFilters)
use a field picker for the biocache field sourced from https://biocache.ala.org.au/fields?filter=
split "filter" into three fields negate, field, and value

**Comment by Tasilee** [comment]
@M-Nicholls - I can't see these links so could you add my (gmail) credentials please?

**Comment by alexhuang091** [comment]
<img width="873" alt="Screen Shot 2020-04-28 at 4 57 57 pm" src="https://user-images.githubusercontent.com/61677987/80456798-8beb8800-8971-11ea-89e1-f1b8b482a10d.png">
<img width="877" alt="Screen Shot 2020-04-28 at 4 58 07 pm" src="https://user-images.githubusercontent.com/61677987/80456806-8e4de200-8971-11ea-98b3-49b66d503568.png">

I've done some very basic UI, there's a button to toggle 'Exclude', an input to accept user input filter value, and a text area (which will be read-only) which display concatenated fq.

Let me know your ideas especially the 'Exclude' toggle button. Or if you have a better idea how to do 'negate'.

**Comment by alexhuang091** [comment]
or it can be a dropdown list with '+'/'-' or 'Include'/'Exclude'. The default value is '+'/'Include'
