### ISSUE TITLE
populate or improve the DQ filter biocache field descriptions

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#80]
for the fields used in the DQ filters

populate or improve the biocache field descriptions (https://biocache.ala.org.au/fields?filter=) where the description is not sufficient to describe the DQ filter fields

To Do:
Create wiki page for each field
Include headings for:
Name of field (Title of page) - format is lowercase_lowercase)
Short description
Description
Relevant standards
Expert vocabulary
ALA usage

**Comment by M-Nicholls** [comment]
o	more detail and ever more detail as to what the data test actually is (formulas, thresholds etc.).
o	Data Quality assertions is a bit of a mystery sometimes.
o	Information about default data quality filters would be useful.

**Comment by M-Nicholls** [comment]
manually edit and deploy the properties file

**Comment by RobinaSanderson** [comment]
Pages are created using the information on the spreadsheet in Miles' one drive: https://csiroau-my.sharepoint.com/:x:/g/personal/nic24a_csiro_au/EUOTwwinM6JLhoyRK0r_xBoBurizE2hv8CPQxEVt-thfbQ?e=bZIqaL

@M-Nicholls  These pages don't include formulas or thresholds or a code reference link. Do we want another ticket for this technical information?

**Comment by M-Nicholls** [comment]
I've added a code reference to each page I think that's enough for now unless user feedback indicates they need more information.

just need to finish this ticket so the meta data is visible: https://github.com/AtlasOfLivingAustralia/DataQuality/issues/116

**Comment by M-Nicholls** [comment]
[messages_properties.txt](https://github.com/AtlasOfLivingAustralia/DataQuality/files/4909903/messages_properties.txt)
this needs to copied into the messages.properties file

**Comment by M-Nicholls** [comment]
Need to review and edit the #download field descriptions section of messages.properties: https://github.com/AtlasOfLivingAustralia/biocache-service/blob/2c013e15d88350671ced5cabfe6781695d816fb9/src/main/webapp/WEB-INF/messages.properties

description.field_name=longer plain text description

**Comment by alexhuang091** [comment]
Hi Miles, as you can see, description.fieldName is set into info. But what we want to update is the description which now comes from facet.fieldName which we can't change directly since it's used somewhere else.

<img width="1185" alt="Screen Shot 2020-07-14 at 9 57 08 am" src="https://user-images.githubusercontent.com/61677987/87365055-8db00980-c5b8-11ea-99f2-b58f7bebd5f6.png">

One solution is to add lines like 
```
info.assertions=A list of all assertions (user and system supplied) for a record resulting from data quality tests
info.coordinate_uncertainty=A radius in metres defining the smallest circle the location could occur within
info.geospatial_kosher=An indication of whether a record is spatially valid or not
info.outlier_layer_count=The number of envinonmental spatial layers for which this record has been identified as an outlier by the Reverse Jackknife method
info.taxonomic_issue=Lists any taxonomic data quality issues detected
info.duplicate_status=Identifies suspected duplicates (D), and what appears to be the best representation of suspected duplicate records (R)
info.occurrence_status=A statement about the presence or absence of a taxon at a location.
info.occurrence_decade_i=The decade for this record e.g. 1910
```

So if info.fileName exists, it's assigned to description, else fallback to existing solutions. This way only these 8 fields with new description will be affected.

**Comment by alexhuang091** [comment]
So if description.field_name is updated, **info** and '**Filter Info**' in below and will changed accordingly

<img width="840" alt="Screen Shot 2020-07-14 at 10 38 59 am" src="https://user-images.githubusercontent.com/61677987/87367438-57758880-c5be-11ea-8358-d9696e1ef91d.png">

<img width="588" alt="Screen Shot 2020-07-14 at 10 39 24 am" src="https://user-images.githubusercontent.com/61677987/87367445-5cd2d300-c5be-11ea-90e0-81b8ca4bdc01.png">

**Comment by M-Nicholls** [comment]
we could also add the link to the wiki page to the description.field name / info similar to the DwC links - that way we don't need an extra field in all three layers for the link

**Comment by M-Nicholls** [comment]
These lines need to be added/updated in the messages.properties file:


description.basis_of_record=What this is a record of e.g. specimen, human observation, fossil. Wiki: https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/basis_of_record
description.duplicate_status=Identifies suspected duplicates (D), and what appears to be the best representation of suspected duplicate records (R). Wiki: https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/duplicate_status
description.taxonomic_issue=Lists any taxonomic data quality issues detected. Wiki: https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/taxonomic_issue
description.occurrence_decade_i=The decade for this record e.g. 1910. Wiki: https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/occurrence_decade_i
description.occurrence_status=A statement about the presence or absence of a taxon at a Location. Wiki: https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/occurrence_status
description.geospatial_kosher=An indication of whether a record is spatially valid or not. Wiki: https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/geospatial_kosher
description.assertions=A list of all assertions (user and system supplied) for a record resulting from data quality tests. Wiki: https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/assertions
description.coordinate_uncertainty=A radius in metres defining the smallest circle the location could occur within. Wiki: https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/coordinate_uncertainty
description.outlier_layer_count=The number of envinonmental spatial layers for which this record has been identified as an outlier by the Reverse Jackknife method. Wiki: https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/outlier_layer_count

**Comment by alexhuang091** [comment]
There's a logic in biocache-service: if a field has a valid dwcTerm and dwcURL, they will be appended to info so you can see something like this:

![Screen_Shot_2020-07-14_at_2_18_16_pm](https://user-images.githubusercontent.com/61677987/87383981-f78eda00-c5dd-11ea-9ef3-27d950973f06.jpg)

**Comment by M-Nicholls** [comment]
ok, let's remove the wiki links from the  description.fieldname text and we'll look at adding link as a separate issue
