### ISSUE TITLE
DQ filter profiles

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#83]
Admin function to save a set of DQ filters as a DQ profile - e.g. ALA base DQ filter, suitable for modelling, nominated by SA government as quality data

description of the profile
set of DQ filters

user can select a DQ profile in the DQ filters UI

**Comment by M-Nicholls** [comment]
another category of filter above the categories - with a title and description

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/biocache-hubs/review/BH-CR-24

**Comment by M-Nicholls** [comment]
If a profile is deleted when in use then the URL doesn't update and no DQ filters are visible/applied

e.g. https://biocache-dq-test.ala.org.au/occurrences/search?q=*%3A*&fq=state%3A%22Australian+Capital+Territory%22&qualityProfile=3

this isn't urgent as it's not anticipated that entire filter profiles will often be deleted but the expected behavior would be to check if the requested profile exists and if not return to the default

**Comment by M-Nicholls** [comment]
edit button on the profile admin selection screen doesn't allow editing of the profile name, description etc

**Comment by M-Nicholls** [comment]
when creating a profile need to be able to add a description

**Comment by M-Nicholls** [comment]
bug found in the demo

**Comment by peggynewman** [comment]
Would be great to include an author, or owner with contact details for each profile

**Comment by M-Nicholls** [comment]
bug from demo - if choose a facet with a different profile applied it goes back to the default profile
