### ISSUE TITLE
DQ filter testing feedback

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#88]
•	Rename  heading  ‘Quality filters applied’ to   Default Data Quality filters  (people who don’t have our background of this data quality project are confused when first see this box).
•	Info button needs layman description – can keep tech script as well but many  users cant decipher what is provided.
•	Dates default not appropriate - leave all valid dates in  or maybe filter out  historic records (say older than 50years)  - or leave in but use another colour – or leave in the filter list at the top as on option to exclude (keep default as include). My  preference  depends on what is possible for your programmers. I initially thought Date filter was going to show no date provided or poor date accuracy.
•	When in map view and you turn a  default on it refreshed in record view so you cant see the change at a glance - bring them in in a different  colour or refresh the change in filter staying  in MAP view. (new issue created https://github.com/AtlasOfLivingAustralia/DataQuality/issues/89)
•	Quality filters on left show 4  -it  took me a while before I realized I could scroll  down to see the  others. The arrow that says convert this data quality filter into separate ………. Is not very clear . I will need to investigate more to be sure what it does.
•	Outlier – info button says 3-* but where does user go to understand this.
•	Data Quality assertions is a bit of a mystery sometimes. I have tried to unravel those fields that return ‘false’ in the download outputs but not always go the result I expected. Maybe that’s for another  Sprint.

**Comment by Tasilee** [comment]
Thanks Heather, you are exceptional, as ever.

Two more to go...

Lee


From the (i)Pad

**Comment by M-Nicholls** [comment]
Some quick thoughts jotted down during the meeting as suggested;

-A larger/more obvious label to explain where the filter has been broken down and that its pieces can be excluded/included selectively.  I did not realise that this was possible when I played around before the demo.  This is very useful/powerful, but not obvious (to me).
-Filter descriptions – more detail and ever more detail as to what the data test actually is (formulas, thresholds etc.).  This may require another level of drill down.
-I agree absence records should be out by default – far to easy to interpret them as present!
-Fossil records may be best colour coded or something so it’s obvious that it is a fossil (the management considerations are very different)!

-Date ranges, what date ranges people want data from is highly variable depending on their purpose.  Hard to get a one size fits all here.

-Data points on the coastline can get flagged as wrong habitat, when they may only be out by a few metres, well within the supplied position accuracy.  These are still useful points and are being penalised for being on the coast. Some examples, sea shell collected from the beach (checked), beached whales (I haven’t seen this but probably affected).

Having the tests at the top and in the facets is good in some ways – but perhaps it would be easier to use if there was just one set of controls on the screen – more space could then be used to help display them clearly (this is just an idea, not a real issue per se).

It's all looking pretty good though – and should make getting good data out much easier.

**Comment by M-Nicholls** [comment]
I was wanting to see if/how the DQ filters were documented when I downloaded a set of records.

**Comment by M-Nicholls** [comment]
Overall looks good.
It took me a while to realise that you can adjust the default values via the selection on the left.
It might ease peoples confusion if the left hand column was in the same order as the selectable items across the top.

**Comment by M-Nicholls** [comment]
•	Not all erroneous records excluded when applied filters -
Review specimen records: if record coordinates of institution NOT where collected should be excluded? 
https://biocache-dq-test.ala.org.au/occurrences/b719799e-260e-4041-b68c-0f27b1615c02. 
I've found the Herbarium list 'ex-situ' populations - these only excluded if a date mismatch on ID vs start date. https://biocache-dq-test.ala.org.au/occurrences/cf21ac62-457e-47a1-aa60-6a30579427fb
 
Is centre of country working as an exclusion filter?  See record where there appears to be a NT observation of a SA/Vic spp: 
https://biocache-dq-test.ala.org.au/occurrences/search?taxa=Caladenia+concolor#tab_mapView  - should have failed the tests applied by the filters.
 
Maybe as an addition to this there could be an option to deselect additional records. Like a user defined filter or a spatial deselect? Reason: Users that regularly have the same requirements for selection then could add/ remove own filter set as needed. Only works with login etc. but also over time could influence your decisions on refining these filters based on frequency of people applying their defined selections.

**Comment by M-Nicholls** [comment]
•	Filter out absence records
•	Subfossil records
•	Date filter – 1950 or 1980 -> 
•	Take out dates that are inaccurate
Annotations – when updated in source the annotation needs to be updated on the records as well
•	Sensitive records
o	Is this interacting with the filters – habitat and coordinate uncertainty
•	Mapping – when filters are turned off it resets back to the list view – need to see the changes on the map
•	When turning records on/off show them differently on the map – so you can see the impact of the filter on the map

**Comment by alexhuang091** [comment]
> Quality filters on left show 4 -it took me a while before I realized I could scroll down to see the others
<img width="309" alt="Screen Shot 2020-05-15 at 9 38 48 am" src="https://user-images.githubusercontent.com/61677987/81996342-1a5d4a80-9690-11ea-8b6c-2ae2810c7d07.png">

can we add something similar to 'choose more'? User right now can only untick one by one and each enable/disable will trigger a query. If there's a dialog, user can enable/disable multiple and when the dialog is closed one query is fired.

**Comment by M-Nicholls** [comment]
Some of the data quality filters underlying this functionality are a bit blunt.  For instance this record https://biocache-dq-test.ala.org.au/occurrences/968e9b3c-97f3-4517-86b2-59c63bc2654d
Appears to be fine to me, but it fails the spatial filter for not being in the ocean (although the maps shows it to be (just) - and it fails the date test - although a valid date is supplied (with no date precision though).  I appreciate that this example is in a  bit of a grey zone and you have to make a cut somewhere though
Habitat incorrect for species would be good if the data was reliable but I have found many species that were flagged as marine and they were clearly terrestrial and vice versa- How is this flag applied?
There are also terrestrial species close to the coast that have been flagged but when I zoomed in they were actually on land so a bit more spatial latitude is needed.
 
It appears that many INaturalist records are being loaded without dates so they are being filtered out but I would have thought that the loading system would include dates automatically.
The museums and herbariums hold many records that are pre 1900. You can remove the filter but would you have to create your own filter in the normal way if you wanted a different date range. I think a different type of date filter is needed.
 
I came across some records from our BDBSA data that would be excluded by user assertions "unconfirmed" that have a history - the record had been flagged and I fixed it in the source data and added my assertion before the latest refresh of our data in ALA. So it is now correct in ALA but the assertion is still unconfirmed so the record would be filtered out. Who is the data custodian who could clear it? Not sure about the process. 
Thanks for the opportunity to test. This is looking good. 

Some feedback:
1. If I search for a species it shows how many records there are but I don't know how many records are displaying below. Do I need to add each number to determine who many records are displaying with the filter or without? 

2. There are a lot of icons which are quite small on the filters - perhaps there is a way to make that more transparent?

3. Information about default data quality filters would be useful. 

4. Is there a way to have a graphical representation of the filters being applied? e.g. obis.org/country/13

**Comment by M-Nicholls** [comment]
I’ve done little testing, but have many fundamental questions. 

•	How are state supplied (Bionet) suspect records being processed.  Are they filtered? 
•	Are there standards around how states describe suspect records?
•	How are problem records that are annotated in ALA handled  - Can these flags be filtered out?
•	How are these annotations currently communicated back to custodians particularly state aggregators?
•	How are generalised location coordinates from the states handled eg some records sensitive species locations can be upto10km out of true position?.  
•	Are there standards for how locations denaturing is communicated by states? 
•	Definitions are being developed for quality filter fields which is great. Are these published outside of the application or only via the application? 
•	Will definitions be developed for all ALA fields delivered through the ALA api ? if so, how will these definitions be made available to not application users (eg API users)?

If we are able to address solutions for these we will be in a pretty good position. As you can see effective solutions will need to extend beyond just application enhancements themselves.

**Comment by M-Nicholls** [comment]
Key things from me:

•	Profiles – good this is on the list;  communities may want to consider setting up a definition?
•	Need a document that provides a definition of filters and their derivation
o	This will also help review of the currently configured filters
•	Inclusion of filters in the metadata of a download
•	(assertions – good to work out so issues are closed;  note that I get some feedback via email from users after they have downloaded data…  so that will not be captured in the ALA against the records.  Think this unavoidable, so really FYI.)
•	Good to see the reverse of the filters so providers can improve data quality.
•	Note for myself – sharing with you as a use case:  explore the download/api options –  include all the DQ filters  in the download/return  ->  how could we incorporate into our internal DQ processes

**Comment by M-Nicholls** [comment]
•	Filter out absence records
•	Subfossil records
•	Date filter – 1950 or 1980 -> 
•	Take out dates that are inaccurate
Annotations – when updated in source the annotation needs to be updated on the records as well
•	Sensitive records
o	Is this interacting with the filters – habitat and coordinate uncertainty
•	Mapping – when filters are turned off it resets back to the list view – need to see the changes on the map
•	When turning records on/off show them differently on the map – so you can see the impact of the filter on the map

**Comment by M-Nicholls** [comment]
this has all been split out into other issues
