### ISSUE TITLE
stay on map tab when applying DQ filters

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#89]
When in map view and you turn a default filter off it refreshed in record view so you cant see the change at a glance - the window should stay in MAP view.

**Comment by alexhuang091** [comment]
I'm sure I saw it on Tuesday but can't reproduce on my machine. Tried both Firefox and Chrome.

**Comment by M-Nicholls** [comment]
can't replicate - we'll have to check in production
