### ISSUE TITLE
DQ filters applied to downloads

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#91]
Data quality filters need to be applied to downloads (the record count must match the record count in the interface) and displayed in the DOI page and downloaded file readme.html 

the DOI page and  readme.html to show:

Atlas of Living Australia occurrence download at https://biocache-dq-test.ala.org.au/occurrences/search?q=*%3A*&fq=sensitive%3A%22generalised%22&fq=state%3A%22Australian%20Capital%20Territory%22 accessed on Mon May 18 14:12:36 AEST 2020.

Data Quality filters applied:
list of DQ filters applied and their fq

The full URL to regenerate the same data set as if the filters were not present (in case the filters change over time)

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/downloads-plugin/review/DP-CR-2
https://upsource.ala.org.au/doi-service/review/DS-CR-4
https://upsource.ala.org.au/biocache-hubs/review/BH-CR-31
https://upsource.ala.org.au/biocache-service/review/BS-CR-3

**Comment by M-Nicholls** [comment]
**To Do**
help doco on downloads - when you click the download URL it puts the DQ filters as user filters and switches off the DQ filters - because filters may have changed

**Fixes**
- Return to search results should just go back to previous state

- URL in the citation text in the email and readme.html is too long - use the DOI e.g.
When using this dataset please use the following citation: 
Atlas of Living Australia occurrence download https://doi.org/10.80416/TEST_DOI_5edec63217497

- When the filters are disabled and records are downloaded then the most recent filter profile is still visible in the URL and the filters are applied in the search URL
e.g. https://doi-test.ala.org.au/doi/10.80416/TEST_DOI_5edecb37bba47

It should just have the Data Quality filters have been disabled for this search  and any user filters

**Comment by M-Nicholls** [comment]
set up a download and then once it is running click "Return to search results": 

Application error

    Error from server at http://aws-sc1b.ala:8983/solr/biocache: org.apache.solr.search.SyntaxError: Cannot parse '[species_group:"Amphibians\",\ sensitive\:\"generalised"]': Encountered " <RANGE_GOOP> "sensitive\\:\\\"generalised\" "" at line 1, column 31. Was expecting: "TO" ...

**Comment by M-Nicholls** [comment]
remaining bug moved to https://github.com/AtlasOfLivingAustralia/DataQuality/issues/133
