### ISSUE TITLE
View DQ filter profile metadata page

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#96]
accessed via an info button next to the profile selection drop down (mouse over - "Profile description")

view a page describing the DQ profile - formatted read only view of the admin page with full text visibility of profile and individual filter information
include contact name and email

what sort of window? - try a modal and check if it's readable

**Comment by M-Nicholls** [comment]
filter owner/contact point

**Comment by alexhuang091** [comment]
A basic dialog

<img width="629" alt="Screen Shot 2020-05-21 at 11 53 32 am" src="https://user-images.githubusercontent.com/61677987/82531259-586fd800-9b82-11ea-85c3-d98324da71c0.png">

**Comment by alexhuang091** [comment]
Or can make tables collapsable
 
<img width="631" alt="Screen Shot 2020-05-22 at 10 50 47 am" src="https://user-images.githubusercontent.com/61677987/82619761-2a3dd700-9c1a-11ea-8aed-e70eae2061b9.png">

**Comment by alexhuang091** [comment]
Or make the tables collapsable 

<img width="630" alt="Screen Shot 2020-05-22 at 10 53 37 am" src="https://user-images.githubusercontent.com/61677987/82619954-a506f200-9c1a-11ea-9a4a-a8b0a4c9b646.png">

**Comment by M-Nicholls** [comment]
change the title to "Data quality profile description"

change "contact person" to "Owner"
additional field for "Contact" - to contain the email address

check the width and layout e.g. for the Quality assertions category

Remove the list of categories "Categories in the profile" section and put the info in each category:

Categories

Record type          Enabled
environmental DNA records excluded

Filter description | Filter value | Enabled
eDNA records excluded | -basis_of_record:"EnvironmentalDNA" | true
Fossil records excluded | -basis_of_record:"Fossil specimen" | true

Duplicate    Enabled

Remove duplicate data
...
