### ISSUE TITLE
Filter Profile bugs

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#97]
bug from demo - if choose a facet with a different profile applied it goes back to the default profile
when creating a profile need to be able to add a description
Would be great to include a Contact name and email (optional) with details for each profile
edit button
If a profile is deleted when in use then the URL doesn't update and no DQ filters are visible/applied

e.g. https://biocache-dq-test.ala.org.au/occurrences/search?q=*%3A*&fq=state%3A%22Australian+Capital+Territory%22&qualityProfile=3

this isn't urgent as it's not anticipated that entire filter profiles will often be deleted but the expected behavior would be to check if the requested profile exists and if not return to the default

**Comment by M-Nicholls** [comment]
enable edit button for the DQ filter profile in the admin screen

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/biocache-hubs/review/BH-CR-27

**Comment by M-Nicholls** [comment]
all tested ok
