### ISSUE TITLE
Display assertion descriptions in filter group info as per record details page

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#99]
*note - this UI is getting crowded, any suggestions for how to display the assertions descriptions?

display the description of the DQ assertion in a separate dialogue (like the one on the record details page) when the filter value is clicked.

e.g. 
 -assertions:"habitatMismatch" - habitatMismatch mouse over is
 
COORDINATE_HABITAT_MISMATCH
Marine species reported in terrestrial area. Detection is also dependent on high-resolution coastline at the time of recording, e.g., estuaries can change quickly (LB).
 Wiki page

source the assertions descriptions as per the record details page - the (?) button next to the assertion on e.g. https://biocache-dq-test.ala.org.au/occurrences/8be0e5a3-1d34-43f7-b256-3089f9f2476d#dataQuality (open up the "Show/Hide 49 tests that have not been run" to see that particular test)

*note - this filter group info UI is getting crowded, any suggestions?

**Comment by M-Nicholls** [comment]
we could update the description in the properties file and not change the filter group info dialogue
where else are those definitions in the properties files used?

**Comment by M-Nicholls** [comment]
functionality looks good although some descriptions are referencing the incorrect description e.g. 
zeroLongitude has the description: 
COORDINATE_SUSPECT_NUMBER_DECIMAL_PLACES
Latitude and or longitude has a suspect number of decimal places. GPS receivers typically measure decimal degress to a maximum of 7 decimal places.

**Comment by alexhuang091** [comment]
> zeroLongitude

At least the description is the same as what is displayed in record details

<img width="734" alt="Screen Shot 2020-06-15 at 9 13 11 am" src="https://user-images.githubusercontent.com/61677987/84606333-9bef0500-aee8-11ea-9bc2-467a9d03ca0e.png">

I'll check the sourcecode for more info

**Comment by M-Nicholls** [comment]
OK we just need to get the definitions updated as per https://github.com/AtlasOfLivingAustralia/DataQuality/issues/101
